# Generated by Django 5.1.4 on 2024-12-30 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('position', models.PositiveIntegerField()),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GrandPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('team_principal', models.CharField(max_length=100)),
                ('chassis', models.CharField(max_length=100)),
                ('power_unit', models.CharField(max_length=100)),
                ('championships', models.PositiveIntegerField()),
                ('victories', models.PositiveIntegerField()),
                ('pole_positions', models.PositiveIntegerField()),
                ('fastest_laps', models.PositiveIntegerField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('position', models.PositiveIntegerField()),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_flag', models.URLField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('podiums', models.PositiveIntegerField(blank=True, null=True)),
                ('victories', models.PositiveIntegerField(blank=True, null=True)),
                ('races', models.PositiveIntegerField(blank=True, null=True)),
                ('championships', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='f1legacy.team')),
            ],
        ),
    ]
