# Generated by Django 5.1.4 on 2024-12-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base', models.CharField(max_length=100)),
                ('team_principal', models.CharField(max_length=100)),
                ('chassis', models.CharField(max_length=100)),
                ('power_unit', models.CharField(max_length=100)),
                ('championships', models.IntegerField()),
                ('victories', models.IntegerField()),
                ('pole_positions', models.IntegerField()),
                ('fastest_laps', models.IntegerField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('podiums', models.IntegerField(blank=True, null=True)),
                ('victories', models.IntegerField(blank=True, null=True)),
                ('races', models.IntegerField(blank=True, null=True)),
                ('championships', models.IntegerField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='f1legacy.team')),
            ],
        ),
    ]
