# Generated by Django 5.1.4 on 2024-12-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1legacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='country_flag',
            field=models.URLField(blank=True, null=True),
        ),
    ]
